// ===================================================================
// DADOS COMPARTILHADOS — CIPA 2026/2027
// Incluído em index.html (urna) e mesario.html
// ===================================================================

// --- BANCO DE USUÁRIOS ELEITORES ---
const USUARIOS = [
  { codigo: '005', nome: 'DANIEL SANTOS CERQUEIRA ROCHA' },
  { codigo: '009', nome: 'Jefferson de Oliveira Muniz' },
  { codigo: '012', nome: 'Erika Shimanuki Muta' },
  { codigo: '013', nome: 'Lidiomar José Landim' },
  { codigo: '014', nome: 'Luiz Carlos Machado Chaves' },
  { codigo: '015', nome: 'Silvio Piazera' },
  { codigo: '022', nome: 'MANAUS DA SILVA SOUZA' },
  { codigo: '023', nome: 'LUIS CARLOS DOS SANTOS' },
  { codigo: '026', nome: 'DIEGO FERREIRA GAIOZO' },
  { codigo: '028', nome: 'PAMELA MUTA' },
  { codigo: '030', nome: 'MONICA PINHEIRO AMAZONAS' },
  { codigo: '039', nome: 'WAGNER LUIZ DA SILVA' },
  { codigo: '043', nome: 'FELIPE CARVALHO CAETANO' },
  { codigo: '044', nome: 'RODRIGO VALIN DOS SANTOS' },
  { codigo: '048', nome: 'DAVI APARECIDO VALENTIM' },
  { codigo: '053', nome: 'RODRIGO DA SILVA' },
  { codigo: '057', nome: 'WILLIAM ALVES NASCIMENTO' },
  { codigo: '059', nome: 'ADEMIR DE ALMEIDA MOREIRA' },
  { codigo: '060', nome: 'DAVI BATISTA DA SILVA' },
  { codigo: '063', nome: 'ALEXSSANDER WALLAN OLIVEIRA ROCHA LINO' },
  { codigo: '064', nome: 'JOSUE CARVALHO DE OLIVEIRA' },
  { codigo: '065', nome: 'LEANDRO DE CAMARGO FONSECA' },
  { codigo: '066', nome: 'LEONARDO DORIA MOREIRA' },
  { codigo: '068', nome: 'DANIEL RODRIGUES DA SILVA NETO' },
  { codigo: '069', nome: 'RAFAEL HENRIQUE SHIMADA' },
  { codigo: '071', nome: 'MAURICIO MASSAO TERAMOTO' },
  { codigo: '072', nome: 'WERIGUE BRAGA DE OLIVEIRA' },
  { codigo: '074', nome: 'ALESSANDRO DA SILVA SANTOS' },
  { codigo: '075', nome: 'IONE DE SOUZA' },
  { codigo: '077', nome: 'LOURDES VALERIO DE PONTES' },
  { codigo: '078', nome: 'GUILHERME ROCHA DIAS DE QUEIROZ' },
  { codigo: '080', nome: 'CINTIA CEZARIO DE CARVALHO' },
  { codigo: '082', nome: 'WESLLEY DOS SANTOS RODRIGUES XAVIER' },
  { codigo: '084', nome: 'DIEGO APARECIDO DOS SANTOS GOTO' },
  { codigo: '086', nome: 'MARIA GABRIELA DE SOUZA CUBA' },
  { codigo: '088', nome: 'ALAN VICTOR DE ANDRADE' },
  { codigo: '089', nome: 'LEANDRO MOREIRA' },
  { codigo: '090', nome: 'PIERRE MARCELO DE SOUZA' },
  { codigo: '092', nome: 'EVERTON MATHEUS VILAS BOAS' },
  { codigo: '099', nome: 'ELAINE CRISTINA MACIEL BRITO' },
  { codigo: '100', nome: 'ELOY PRADO DE BRITO' },
  { codigo: '102', nome: 'REGINA REIS CARVALHO' },
  { codigo: '104', nome: 'ADILSON GOMES DA SILVA' },
  { codigo: '107', nome: 'LUIZ EDUARDO DOS SANTOS ALMEIDA' },
  { codigo: '108', nome: 'RONALDO DOS SANTOS' },
  { codigo: '109', nome: 'WELLINGTON DIEGO DE SOUZA NOGUEIRA' },
  { codigo: '110', nome: 'GLAUCIA LISBOA SOUZA SILVA' },
  { codigo: '112', nome: 'GUILHERME MUNIZ DA SILVA' },
  { codigo: '113', nome: 'JEOSMAR MASSONI DE OLIVEIRA' },
  { codigo: '116', nome: 'TANIA CONSULO' },
  { codigo: '117', nome: 'JOSÉ OTAVIO DA SILVA' },
  { codigo: '118', nome: 'RODRIGO DA SILVA' },
  { codigo: '121', nome: 'GABRIEL ANTONIO CHAGAS' },
  { codigo: '122', nome: 'ADEMIR MENDONÇA' },
  { codigo: '124', nome: 'CICERO ALAN SILVA' },
  { codigo: '131', nome: 'ALEXANDRE DE PAULA ALVES FRANCISCO' },
  { codigo: '132', nome: 'ANGELINA MARIA MAGALHAES' },
  { codigo: '135', nome: 'SEBASTIAO MARCIO DA SILVA' },
  { codigo: '136', nome: 'LEANDRO SEBASTIÃO DE ALMEIDA' },
  { codigo: '137', nome: 'RUAN PABLO SANT ANA DA SILVA' },
  { codigo: '138', nome: 'CAROLINA MUTA' },
  { codigo: '139', nome: 'PAULO RICARDO DE ALMEIDA' },
  { codigo: '142', nome: 'JOÃO PAULO OLIVEIRA SILVA' },
  { codigo: '143', nome: 'CLAUDIO PEREIRA DOS SANTOS' },
  { codigo: '147', nome: 'MARIA TEREZINHA LEMOS DE OLIVEIRA' },
  { codigo: '156', nome: 'FERNANDO HENRIQUE MONTEIRO CURSINO' },
  { codigo: '158', nome: 'MARCELO HUMBERTO DA SILVA' },
  { codigo: '167', nome: 'GILMAR DE SOUZA GARCIA' },
  { codigo: '169', nome: 'DANIEL DE ALMEIDA' },
  { codigo: '174', nome: 'MATHEUS VENTURA DA SILVA' },
  { codigo: '175', nome: 'ALCINO VIEIRA GOMES' },
  { codigo: '176', nome: 'MARCELO FELISBERTO CORREA' },
  { codigo: '177', nome: 'CARLOS ALEXANDRE DE ANDRADE' },
  { codigo: '178', nome: 'MARIA APARECIDA CORREIA' },
  { codigo: '179', nome: 'DIOGO JACOB LUCCAS' },
  { codigo: '180', nome: 'VICTOR AUGUSTO ARAUJO DE LIMA' },
  { codigo: '181', nome: 'RAFAEL JUNIO RODRIGUES DA SILVA' },
  { codigo: '185', nome: 'RONALDO DA SILVA' },
  { codigo: '186', nome: 'VIVIANE APARECIDA DE MIRANDA SOUZA' },
  { codigo: '187', nome: 'FILIPE MASSARI SCHULZ' },
  { codigo: '189', nome: 'MARIA DO SOCORRO BORBA DA SILVA' },
  { codigo: '190', nome: 'JONATHAN RAMIM' },
  { codigo: '191', nome: 'SERGIO LEMES DINIZ' },
  { codigo: '192', nome: 'MAICON SOARES DA SILVA' },
  { codigo: '195', nome: 'VANIA MARIA BRAGA' },
  { codigo: '198', nome: 'GUSTAVO PEREIRA DA SILVA' },
  { codigo: '199', nome: 'EMERSON ZANCA' },
  { codigo: '205', nome: 'RAPHAEL MOREIRA DA SILVA LOURENCO' },
  { codigo: '210', nome: 'DANIELLA BRAGANÇA ALVES' },
  { codigo: '211', nome: 'ELOI SIQUEIRA MOREIRA' },
  { codigo: '213', nome: 'STANLEY EDUARDO FARIA DA SILVA' },
  { codigo: '215', nome: 'NOELY PEREIRA LIMA' },
  { codigo: '216', nome: 'THIAGO ALBERIGI LIMA' },
  { codigo: '218', nome: 'FELIPE RAFAEL DOS SANTOS' },
  { codigo: '219', nome: 'GABRIEL MATEUS DOS SANTOS' },
  { codigo: '221', nome: 'BRUNA JENIFER GONÇALVES MACHADO' },
  { codigo: '223', nome: 'POLYNE FERNANDES BENEDITO' },
  { codigo: '226', nome: 'DANIEL LISBOA SOUSA SANTOS' },
  { codigo: '229', nome: 'MAIARA SILVA PIRES DE CAMARGO' },
  { codigo: '230', nome: 'MARILISE KATIA NASCIMENTO PAULA' },
  { codigo: '231', nome: 'MATHEUS AUGUSTO SIQUEIRA LUCIANO' },
  { codigo: '233', nome: 'YOHAN DINIZ RIBEIRO' },
  { codigo: '235', nome: 'MILENA VITORIA DA SILVA IZIDORO' },
  { codigo: '236', nome: 'GISELE APARECIDA ALVES' },
  { codigo: '238', nome: 'MARCELO MOREIRA DE SOUZA' },
  { codigo: '239', nome: 'TIAGO DE OLIVEIRA' },
  { codigo: '241', nome: 'BRUNA COSTA PINTO' },
  { codigo: '243', nome: 'ALINE DE SOUZA GUEDES' },
  { codigo: '244', nome: 'ISALEM EVANDRO SIMÃO' },
  { codigo: '245', nome: 'MICHELLE BENJAMIM DOS SANTOS' },
  { codigo: '248', nome: 'ADRIANO DE SOUZA BERTOLINO DE JESUS' },
  { codigo: '249', nome: 'FERNANDA ALVES DUQUE' },
  { codigo: '251', nome: 'SILVANA APARECIDA LOURENÇO DE OLIVEIRA' },
  { codigo: '252', nome: 'LINALDO RUFINO DOS SANTOS' },
  { codigo: '253', nome: 'ROBERTO FERNANDES DA SILVA' },
  { codigo: '254', nome: 'LUCIANO VIEIRA DOS SANTOS' },
  { codigo: '255', nome: 'SILVIA APARECIDA MACHADO' },
  { codigo: '256', nome: 'MAICON JESUS DA CRUZ REIS' },
  { codigo: '260', nome: 'DANIEL DE PAULA DIAS' },
  { codigo: '262', nome: 'ANTÔNIO AGNALDO DE MORAIS' },
  { codigo: '264', nome: 'JANDERSON FELIX DA SILVA JUNIOR' },
  { codigo: '265', nome: 'RAFAEL PONTES COUTINHO' },
  { codigo: '266', nome: 'CLEIDIANA DOS SANTOS BESSA' },
  { codigo: '268', nome: 'WILLIAN TIAGO SILVA DE ANDRADE' },
  { codigo: '269', nome: 'GUILHERME LUCAS DA SILVA' },
  { codigo: '270', nome: 'PAULO FELIPE DOS SANTOS ALMEIDA' },
  { codigo: '271', nome: 'AISLAN EVERTON DE LIMA SANTOS' },
  { codigo: '272', nome: 'TADEU JOSE DA SILVA' },
  { codigo: '274', nome: 'DANIEL APARECIDO CLARO DE OLIVEIRA' },
  { codigo: '275', nome: 'ANA JULIA MARTINS' },
  { codigo: '276', nome: 'WILLIAN TIAGO SILVA DE ANDRADE' },
  { codigo: '278', nome: 'SILVIA APARECIDA MACHADO' },
  { codigo: '279', nome: 'DANIEL DE PAULA DIAS' },
  { codigo: '282', nome: 'GABRIEL FIRMINO DE LIMA SOUZA' },
  { codigo: '283', nome: 'FRANCISCA ZACARIAS SILVA' },
  { codigo: '285', nome: 'AURINEIDE MARIA DA SILVA OLIVEIRA' },
  { codigo: '286', nome: 'MARCOS SERGIO DA SILVA' },
  { codigo: '287', nome: 'FRANKLIN WELTER DA MOTA' },
  { codigo: '288', nome: 'MIRELLA FIGUEIREDO DE OLIVEIRA' },
  { codigo: '289', nome: 'PEDRO MAICON MACHADO' },
  { codigo: '290', nome: 'FERNANDO LUIS RAMOS' },
  { codigo: '291', nome: 'MARCOS EDUARDO DA SILVA SANTOS' },
  { codigo: '292', nome: 'DANIEL ALEXANDRE SOARES FERREIRA DE LIMA' },
  { codigo: '293', nome: 'LUCAS LEONARDO RAFAEL' }
];

// --- CONFIGURAÇÃO DOS CANDIDATOS ---
const CANDIDATOS = [
  { numero: '13', nome: 'Roberto Fernandes', setor: 'PCP', foto: 'https://i.postimg.cc/C5nkQqV8/Gemini-Generated-Image-56hhzd56hhzd56hh.png' },
  { numero: '22', nome: 'Marcelo Moreira', setor: 'TST', foto: 'https://i.postimg.cc/5NZjnBpC/Captura-de-tela-2026-03-19-080531.png' }
];
